version: '3.8'

services:
  web:
    image: nokutendamanhango/bookie:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
