spring:
  application:
    name: book-service
  datasource:
    url: jdbc:h2:mem:booksdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8280